### ISSUE TITLE
How to access array element?

### ISSUE THREAD

**Issue by KaiserWerk** [datasweet/jsonmap#10]
E.g. from
`{
	"push": {
		"changes": [{
			"forced": false,
			"old": {
				"name": "master" } } ] } }`

get name = master

**Comment by charlotth** [comment]
Hi @KaiserWerk 
Sry for the delay, i hadn't notifications about your issue 

```go
func TestGithubIssue10(t *testing.T) {
	j := jsonmap.FromString(`{ "push": { "changes": [{ "forced": false, "old": { "name": "master" } } ] } }`)
	assert.Equal(t, "master", j.Get("push.changes[0].old.name").AsString())
}
```

**Comment by KaiserWerk** [comment]
Short and concise, thanks! Maybe place this in the README.
